### PR TITLE
Update the footer links

### PR DESCRIPTION
**Pull request by cverna**
Signed-off-by: Clement Verna <cverna@tutanota.com>

### CODE REVIEW

**Comment by pypingou** [comment]
The other links need to be updated but are necessary. The app is AGPL and this was deemed ok as a way to provide the sources of what is deployed

**Comment by cverna** [comment]
Ok so it should link to f27 SRPMS ?

**Comment by pypingou** [comment]
Yup :)

**Comment by pypingou** [comment]
👍 for me! :)

**Pull request merged**
