### PR TITLE
Remove dependency to xappy

### PR DESCRIPTION
**Pull request by cverna**
This PR replaces the dead upstream xappy project by the xapian python bindings. This will allow fedora-packages to be packaged for rhel7.

### CODE REVIEW

**Comment by pypingou** [comment]
Without knowing much, nothing it standing out for me in here. 👍

**Comment by techtonik** [comment]
Here is the list of index and search engines - https://en.wikipedia.org/wiki/List_of_information_retrieval_libraries - of which Elasticsearch seems to get the most hype nowadays.

**Comment by cverna** [comment]
@techtonik I was looking at Whoosh, but since xappy was used only in the indexing (all the code related to the search is using xapian bindings) I decided to keep xapian and just update the indexing.

Also elasticsearch does not seems to be package in epel7.

**Comment by techtonik** [comment]
It seems that packaging is Elasticsearch survival strategy in this non-friendly economics for OSS.

**Pull request merged**
