### PR TITLE
Handle past and future mdapi json keys.

### PR DESCRIPTION
**Pull request by ralphbean**
See https://github.com/fedora-infra/mdapi/commit/c2eafd8d05171fdcb3fd699835c0a44e02088724#commitcomment-14646204 for discussion.

### CODE REVIEW

**Comment by pypingou** [comment]
As there is already a ``changelog`` key in the JSON: https://apps.fedoraproject.org/mdapi/rawhide/changelog/kernel?pretty=1
What do you think of using ``changelogs``?

**Comment by ralphbean** [comment]
Sure!

**Comment by pypingou** [comment]
Cool :)

**Comment by pypingou** [comment]
:+1: for me! :)

**Comment by ralphbean** [comment]
:rocket: :guitar: :moneybag: :dollar: :moneybag: :guitar: :rocket:

**Pull request merged**
