### PR TITLE
Use the same approach as elsewhere to include the bodhi image

### PR DESCRIPTION
**Pull request by pypingou**
Should fix https://github.com/fedora-infra/fedora-packages/issues/164

### CODE REVIEW

**Comment by puiterwijk** [comment]
Looks good to me :+1:

**Comment by pypingou** [comment]
According to git grep this is how it's done elsewhere, but it's un-tested, do we want to merge still?

**Comment by puiterwijk** [comment]
It looks good to me

**Comment by ralphbean** [comment]
This broke the app.

**Pull request merged**
