### PR TITLE
point scm links to pagure instead of cgit

### PR DESCRIPTION
**Pull request by yashvardhannanavati**
Issue #282

### CODE REVIEW

**Comment by pypingou** [comment]
The change looks good to me but also raised a question: is fedora-packages going to be restricted to rpms only?

**Comment by ralphbean** [comment]
It currently has no logic to deal with non-rpms packages.  That would take some significant work.

**Comment by pypingou** [comment]
> It currently has no logic to deal with non-rpms packages. That would take some significant work.

Ok thanks

**Comment by techtonik** [comment]
So is anybody going to fix broken links?

**Comment by genodeftest** [comment]
@techtonik 
> So is anybody going to fix broken links?

Which broken links?

**Comment by genodeftest** [comment]
Any chance to get this merged soon, as #282 is really annoying.

**Comment by techtonik** [comment]
#282 is about broken links, such as https://src.fedoraproject.org/bpython.git

**Comment by techtonik** [comment]
@pypingou thanks. What is the release process to know when it can be tested?

**Comment by pypingou** [comment]
@techtonik it's highly manual process so someone needs to step in and do the release then deploy it. So no real ETA for this

**Comment by techtonik** [comment]
@pypingou is there at least Ansible in the pipeline?

**Comment by pypingou** [comment]
At the end of the process to deploy, I think so

**Pull request merged**
